language: java
sudo: required
install: true

services:
  - docker

addons:
  sonarcloud:
    organization: "lequal"

jdk:
  - oraclejdk8

env:
  - sonarqube: none
  - sonarqube: 5.6.7
  - sonarqube: 6.0
  - sonarqube: 6.1
  - sonarqube: 6.2
  - sonarqube: 6.3.1
  - sonarqube: 6.4
  - sonarqube: 6.5
  - sonarqube: 6.6
  - sonarqube: 6.7
  - sonarqube: 6.7.1
  - sonarqube: 6.7.2
  - sonarqube: 6.7.3
  - sonarqube: 6.7.4
  - sonarqube: 6.7.5
  - sonarqube: 7.0
  - sonarqube: 7.1

script:
  - if [ $sonarqube != "none" ]; then
    mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package;
    chmod +x src/test/it/run-test.sh;
    docker run -d -p 127.0.0.1:9000:9000/tcp sonarqube:${sonarqube}-alpine;
    echo "Waiting 5 minutes for SonarQube...";
    sleep 300;
    mvn sonar:sonar -Dsonar.host.url=http://127.0.0.1:9000 -Dsonar.login=admin -Dsonar.password=admin -Dsonar.organization=default-organization -Dsonar.branch.name= ;
    src/test/it/run-test.sh;
    else mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar;
    fi
  - mvn clean package;
    mvn sonar:sonar;
    mvn sonar-packaging:check;
    mvn sonar-packaging:sonar-plugin

cache:
  directories:
  - '$HOME/.m2/repository'
  - '$HOME/.sonar/cache'

notifications:
  email: false
