dist: xenial
language: java
install: true

services:
  - docker

addons:
  sonarcloud:
    organization: "lequal"
    token:
      secure: "alIypi5kcdqBeX8z1z82iFHwUrNZ1ICke2rUn6eZNyiBxnOBXMqWGUtTZYtkmYMBLZK06pTJ/jtgdyWOwfdw5zZ59cQwylOhWhXK9QRmPJzdeQWPxbRDVbd+c7LWTXOA0WBh96Htzjoz1kd6SaheozsAfxEhhiekvE6gaMMk0ac+hufeUFF80KUDaoY92cu/xqHmWYn4srVvLpSO6WYzAAlCaPu6ugv009qHai0CyURSNqV8KQO+lBiNNrYUf3v1/LffelMA92w0/hqID89l2mWH4rOa5jx97wfc3Ae7pB3MFvG+qTKk24enYAJG8U+HkDkIt8R13w0Cj55wKno9S0LAKIND59BiayiWyhrCjOd2M/KUYwtF/VkqZwZNepoYQe7AY7bHNkZ52Npum/+6c79fMMn4mxDsSjt6PFcBWd0bVpkpDKlimRe7NZ3mh7plobPU8mwzeCE2Rrsw6aKaU0MHR9EFEsI1pfgrjCDdHjnIgrPOYXHY5dkwUkybXin2QJu4pCYWuTg57MAdvnvaydoZxDcChm6VLmQrKUpRFvzyOyWlbRtq/SVWc6mLPzrCucaIB4zK1GKTeDCku+OAfznuA0w4OrDAF/U9DWQl+/mR7MZuD2NMjYO4zk9R5prDqDbvYgh/vvKygnk3oHo2eUDvknw6CbvRueDpplfgIwE="
    

jdk:
  - openjdk8
  - openjdk11

env:
  - sonarqube: none
  - sonarqube: 7.9-community
  - sonarqube: 8.0-community-beta
  - sonarqube: 8.1-community-beta
  - sonarqube: 8.2-community

script:
  - IS_JDK_11=$(java -version 2>&1 |grep "^openjdk version \"11\." > /dev/null && echo $?)
  - if [ $sonarqube != "none" ]; then
      mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package;
      chmod +x src/test/it/run-test.sh;mvn clean package;
      echo "Starting docker";
      docker run --name sonarqube_${sonarqube} -d -p 127.0.0.1:9000:9000/tcp sonarqube:${sonarqube};
      echo "Inject plugin";
      docker cp target/sonar-cnes-report.jar sonarqube_${sonarqube}:/opt/sonarqube/extensions/plugins/;
      docker exec -u root sonarqube_${sonarqube} chmod 777 /opt/sonarqube/extensions/plugins/sonar-cnes-report.jar;
      docker restart sonarqube_${sonarqube};
      echo "Waiting up to 5 minutes for SonarQube...";
      counter=0;
      limit=300;
      status_sonar=$(curl -s "http://localhost:9000/api/system/status" | grep "\"status\":\"UP\"" > /dev/null; echo $?);
      while [[ 0 -ne $status_sonar && $counter -le $limit ]]; do
          sleep 1;
          counter=$(( $counter + 1 ));
          status_sonar=$(curl -s "http://localhost:9000/api/system/status" | grep "\"status\":\"UP\"" > /dev/null; echo $?);
      done;
      mvn sonar:sonar -Dsonar.host.url=http://127.0.0.1:9000 -Dsonar.login=admin -Dsonar.password=admin -Dsonar.organization=default-organization -Dsonar.branch.name= ;
      src/test/it/run-test.sh;
      wget "http://localhost:9000/api/cnesreport/report?key=fr.cnes.sonar%3Acnesreport&author=travis-ci&token=noauth";
    elif [ "${IS_JDK_11}" = "0" ]; then 
      mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar;
    fi

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
    - 'node'
    - 'node_modules'

notifications:
  email: false

deploy:
  provider: releases
  api_key:
    secure: DZXCeGatbBOQ6dyUYAAZOAVd/ORttOq8v8rRjgcfOFk7JcR2DGTu5ICpDriDOadUp24PylLZ8SHEZHJu+JshFXuABP5xIc/Fs+kr2OeFDw/qOPNzwZFWU/WwmlidLzt0O2i1wat7+9fnKEdcBikdC+qayhunT6mdozjhlw8Y+e3USuB/7KECbxPcHs2xf7Ek0eUVjX5Hmp+gi3ryO0Jxk/aHZb+QPdYGvyf8dUcFx/GTrIqfkRu/MbXmU7dnZ9Zp7cFMbC8M2uDSNmGcVgHfXyci5mL4b30JKSHU3kpqZDvb5RVhd1W/WqRErAR1tnp2hlhg4f1fEbYiC0GUZkdfedXnK2cAFYz7ar9g49bS9LjWsWUATtKtSKZf4JZimNn0w/pVI1hUaDhrUdIpA8+Ok8gOSTG6rL3Y1eh54s9JO4EUsX3bWJ/BrZjkkR/TlYIlIN5ejXswZId6ItzchJ6nq/S5XZ5dX2ocZ1d9xVQBlqrFW8U5v5BALVYMjWRjwLaXfumQMYiuCrL9TMggMkJaheWSuQNEY5WDbEnH656v6EmpB9n3/nonxLnF0/37AKerqR+RyPwEOWEApTn0fRyYB/7HfMUJi44MXxGTXuflJWjNXT3bXVt3pUudPGKMPQJ5xJ+9pAwbJZWhhTEq+yfHa1UNOC09dQAVVaZJ8egvMdk=
  file: target/sonar-cnes-report.jar
  skip_cleanup: true
  draft: true
  on:
    branch: master
    condition: $sonarqube = none
    tags: true
    jdk: 'openjdk11'
